# Basic
title: 古墨香
subtitle: 手提眼前墨，笔落古时香
welcome_message: 欢 迎 光 临
description: 古墨香是我的个人书画网站
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://www.gumoxiang.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 墨宝
    description: 前往作品

# Navigation buttons in the front page.
nav:
    - {title: 相关, description: 其它相关, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 古墨香
    github: gongziyayu
    QQ: 1211095289
    weichart: gongziyayu
    gplus: 107108267983477358170
    mail: gongziyayu@gmail.com
# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
