# Basic
title: 古墨香
subtitle: 手提眼前墨，笔落古时香
welcome_message: 欢 迎 光 临
description: 古墨香是我的个人书画网站
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 作品
    description: 前往作品

# Navigation buttons in the front page.
nav:
    - {title: 友情链接, description: 友情链接, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    微博: 
    github:gongziyayu
    QQ: <a href="tencent://message/?uin=1211095289&Site=&Menu=yes">点击此处与我联系</a>
    微信: 107108267983477358170
    mail: gongziyayu@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
